import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import LayoutInterceptor from './layout-interceptor';
import Header from '@/components/header';
import { Sidebar } from './sidebar';
// import './prism-dracula.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <LayoutInterceptor
            wrapper={
              <>
                <Header />
                <main className="flex w-full h-full dark:bg-black bg-white">
                  <Sidebar className="w-1/5 border-r " />
                  {children}
                </main>
              </>
            }
          >
            {children}
          </LayoutInterceptor>
        </Providers>
      </body>
    </html>
  );
}
